@extends("layaouts.plantilla")


@section("head")
<title>Ubica el local</title>
@endsection


@section("body")

<p style="margin: 0 30px; text-align: justify;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate amet vero veritatis omnis doloribus eius, sunt iure, esse velit, rerum dolor nulla. Quidem at fuga, nisi suscipit veritatis illo minima.
        Suscipit accusamus consequuntur ipsa expedita nemo incidunt nesciunt, sunt non eius harum odio illo odit doloribus asperiores molestiae id dolorum architecto deleniti veniam atque, ex, accusantium beatae magni officia! Nam.
        Magni vero pariatur quia. Aperiam nam sed unde. Veniam dolorem tenetur reiciendis, et assumenda sequi facere repellendus, voluptatum odit officia deserunt doloribus rem modi mollitia, neque laborum omnis sed consequatur?
        Maiores suscipit ut, corporis earum totam optio ad quam nostrum? Impedit quos quo officiis suscipit fugiat animi illo, quaerat doloribus, numquam illum cupiditate iste laboriosam odio reprehenderit incidunt minima nesciunt.
        Atque, sit alias sunt laborum qui repudiandae quo odit culpa laudantium architecto distinctio ad, cum maiores assumenda unde commodi natus blanditiis, repellendus perferendis aliquid. Aliquid nihil totam voluptates error placeat.
        Sed quibusdam, eaque ipsum itaque voluptas recusandae eos at. Accusamus adipisci sed culpa similique temporibus numquam in assumenda ratione! Autem aut minus harum laboriosam sint voluptatum. Alias aliquid atque iste?
        Velit cum facere omnis rem dicta cupiditate pariatur libero tenetur dolores perferendis aperiam, quis similique, dolor ut alias quas adipisci cumque deleniti repellat consequuntur neque excepturi amet dolorum consectetur. Repellat!
        Fuga iusto necessitatibus eligendi reprehenderit suscipit nihil quod odio ullam natus recusandae iste nesciunt ad voluptatum ut, voluptas amet itaque laboriosam, voluptates repellat porro sint? Consequatur nihil soluta est ullam?
        Similique, nobis. Ipsam, cumque quaerat aspernatur nesciunt consequuntur quae nulla nisi? Odio itaque, maiores laudantium provident, dolorem officiis totam dolorum alias temporibus ex voluptatum reiciendis corporis enim excepturi sequi tenetur.
        Distinctio asperiores quas debitis maxime tempora aut tenetur, quidem molestias fuga velit dolore delectus deleniti iure eligendi cupiditate vel voluptate quasi pariatur. Excepturi debitis a quae inventore fugit vitae exercitationem?
        Nam fuga, delectus quam voluptatibus nihil totam atque assumenda impedit, tempore maxime reiciendis nobis earum, eos debitis adipisci ea repudiandae tenetur voluptate nemo officia consequuntur sit sed. Assumenda, sunt provident!
        Doloribus optio debitis molestias. Nesciunt, possimus assumenda? Sequi voluptas provident laborum in laboriosam, vitae ratione accusamus facere ex voluptate corporis rerum cum iusto dignissimos dolorem tempora aliquid hic distinctio. Quod!
        Pariatur non laudantium voluptatum in inventore nemo ex, reiciendis provident facere sed atque ipsum tempora eveniet! Dolores ducimus voluptatum exercitationem laboriosam, rerum dignissimos rem obcaecati corporis. Id sapiente ad temporibus!
        Quia quas maxime debitis impedit in laudantium error officia aperiam expedita, dicta, eveniet, inventore quod unde fugit assumenda dolores? Laboriosam eum accusamus tempora quae nam nostrum. Doloremque numquam dolor quidem?
        Saepe dolores explicabo dolorem! Impedit totam quae officia ad voluptatum eum aliquam mollitia vitae sequi eligendi perferendis, quaerat accusantium quis saepe enim, molestiae accusamus eos similique fugiat eaque eius. Soluta?
        Temporibus, similique, ab non odit nobis error sit natus dignissimos culpa totam porro dolore. Illo unde, explicabo sed quidem laudantium distinctio! Totam possimus illo quae ducimus repudiandae, optio cum nihil!
        Libero, inventore temporibus similique accusamus possimus esse consequuntur! Molestiae nam ex nihil voluptate. Ratione expedita deserunt ea nihil voluptas excepturi velit sit reiciendis illum nesciunt, ipsam, tempore, quos cumque modi.
        Non, repellat necessitatibus sint ab maiores quos dolorem beatae totam, voluptatem blanditiis vel corrupti repudiandae dolores quas nostrum molestias sit tenetur hic et. Eius vero ipsa, consequatur quam iure blanditiis!
        Velit accusantium quis magni laboriosam aperiam esse, natus tempora commodi itaque distinctio quidem nobis tenetur ducimus illo vel quia placeat error vitae iusto atque repellendus dolorem unde deleniti assumenda. Eos.
        Nostrum saepe eligendi similique aperiam dolores veniam, in vero impedit quam fuga laborum alias iusto, libero autem voluptatem natus, doloribus ex. Quidem sed asperiores voluptatibus molestias, totam impedit corrupti dolore?
        Nam explicabo debitis unde! Nihil cum aliquam repudiandae facere delectus maiores sit, esse consequatur provident at voluptatum non nisi necessitatibus incidunt. Quae amet minima alias tenetur sapiente accusantium tempora accusamus!
        Soluta facere aliquam ipsam rerum nulla accusamus, modi asperiores, odio assumenda maiores tenetur. Asperiores voluptatibus iure velit deserunt alias, nam labore magni. Ab alias similique et minima sit? Ad, praesentium?
        Dicta molestiae pariatur sunt ex eveniet nam impedit ad sit, praesentium, beatae asperiores maxime! Nemo, ad exercitationem! Itaque laboriosam rerum sit distinctio recusandae vel, ut cumque amet maiores soluta excepturi!
        Non error vero assumenda cupiditate in enim perspiciatis nam, commodi molestias quia voluptas placeat tempore iusto vel ratione nesciunt, ex quidem impedit nobis quo animi deserunt dignissimos. Aspernatur, quidem architecto.
        Laborum cumque iure, veniam voluptas facere quibusdam! Accusantium asperiores odio exercitationem cumque earum, natus dolore necessitatibus, labore, provident facere harum. Modi obcaecati tempora aut quidem blanditiis ipsum nostrum libero voluptate.
        Consectetur corrupti deleniti optio facilis accusamus quia eaque cupiditate officia sed inventore praesentium voluptas ullam, perspiciatis illo ea officiis ratione reiciendis explicabo? At distinctio, voluptatem dolores dolore cumque aut pariatur.
        Iusto magni eum blanditiis consequatur laborum unde! Quos suscipit minus tempora soluta saepe nam, voluptas officia deleniti harum nulla neque voluptatibus qui quidem aliquam unde aperiam. Ipsa laboriosam animi praesentium!
        Cupiditate, delectus quasi? Odio, vitae eos consequuntur facere repudiandae praesentium dolor sequi recusandae voluptatibus! Quam voluptas quidem adipisci, totam deserunt aperiam iure facere error pariatur dolorem, nulla laborum sed qui.
        Dicta voluptas tempora repudiandae aspernatur maxime eos corrupti nihil deleniti eaque consequuntur laborum, obcaecati minus reprehenderit voluptate nam. Adipisci architecto ab nam voluptatum tempora eum, magnam reiciendis amet doloremque nesciunt!
        Ipsa veritatis debitis nostrum cum nemo rerum, non dolore dignissimos fugiat culpa, numquam, nam quae nisi? Veniam dolore tempore pariatur? Suscipit explicabo officia dolor obcaecati magnam repellat voluptatum nisi corrupti.
        Velit delectus doloremque inventore, illo fugiat voluptas perspiciatis ipsum iste suscipit tempora numquam architecto porro aliquam itaque maiores esse laborum vel totam enim eos eveniet illum. Doloremque nemo culpa dolores?
        Fugiat, aliquid modi? Distinctio nobis vitae fugiat reprehenderit. Obcaecati numquam dolore quaerat odio architecto alias, molestiae, debitis, doloribus esse ex soluta voluptatem labore aspernatur ipsum aliquam iusto consequuntur eum laboriosam.
        Corrupti vitae saepe ad similique natus dolore exercitationem facere, voluptatum numquam debitis omnis vel? Aperiam molestias, rerum maxime dolore minus maiores qui dolorem perferendis, voluptatibus totam voluptate ad ipsa explicabo?
        Fuga minima laudantium dolorum odio natus! Dicta temporibus sint eius expedita libero. Voluptates obcaecati eius eveniet atque aliquid corrupti voluptatum minus voluptas rem suscipit nemo illo explicabo alias, incidunt optio!
        Molestiae aut consectetur cupiditate tempore similique cum fuga ut earum perferendis facilis corrupti minus labore eos enim, rerum nisi minima ad, cumque veritatis iste amet. Accusamus exercitationem in numquam tenetur!
        A et iste tenetur cum, quo odit consequuntur. Eius placeat deleniti dolorem commodi atque cupiditate voluptatum recusandae molestiae aliquam incidunt in quidem, aspernatur saepe dolorum cumque quod dolore soluta quis.
        Blanditiis autem, aperiam quaerat porro dolore error illo, necessitatibus veniam tempore voluptatibus cum quas voluptas illum accusamus voluptates officia possimus esse delectus quia officiis laboriosam? Et similique repellat delectus facere.
        Adipisci ab accusantium corrupti dignissimos veniam iure, quas aspernatur, ipsa beatae laboriosam blanditiis distinctio laudantium aperiam officia. Possimus repudiandae similique error, quidem repellendus soluta placeat totam officiis, autem ipsum porro.
        Perferendis, esse quisquam accusamus officia perspiciatis adipisci debitis praesentium laudantium quam! Necessitatibus ullam tempora repellat harum tenetur obcaecati sed eos. Deserunt molestias velit sunt dicta laudantium quos veritatis error neque!
        Sequi ipsam consequuntur magnam sapiente saepe doloribus, laboriosam, quaerat assumenda architecto, exercitationem laudantium molestias! Provident dolorem, aperiam aspernatur expedita ipsum tempora explicabo non officia quas, vitae architecto doloremque omnis asperiores!
        Perspiciatis eius fugiat, sed ea tempore nostrum voluptas omnis amet! Maxime veniam esse ex impedit ratione totam aperiam laboriosam eum magnam reiciendis nobis, praesentium cumque dolore. Provident quisquam voluptas commodi.
        Earum, vitae sequi nemo harum eos rerum voluptatibus non provident. Doloremque odio aliquid harum culpa ut, hic blanditiis accusamus facere ratione nulla sit ipsa dolore officiis voluptates excepturi minima similique.
        Inventore architecto ad incidunt pariatur aut rem harum est soluta voluptates sunt qui optio, quos odit magni deleniti totam quam. Quidem laboriosam modi tempora excepturi reiciendis cupiditate, quis quaerat architecto.
        Harum illum qui, assumenda officia, dignissimos nulla unde consequuntur neque vitae inventore beatae ullam cumque iste facilis quia dolore dolor sequi id. Iusto ducimus vero quos corrupti, hic nulla beatae!
        Earum fugiat, unde minima exercitationem, nesciunt dolores libero cum consectetur, eveniet eius possimus rem et fugit voluptatibus consequatur quis repudiandae officia illum quidem aut porro. Alias obcaecati laborum aliquid autem?
        Aliquid quidem cumque placeat laudantium mollitia vero beatae, illum impedit suscipit dolorum esse officiis? Mollitia magni accusamus asperiores harum temporibus repudiandae maiores, sit sapiente officia, enim voluptatum ipsum obcaecati qui.
        Error, velit? Vero fugit autem repudiandae veritatis illo, ut similique sunt voluptas est laboriosam dignissimos consequuntur placeat, doloremque vel omnis itaque esse corporis asperiores incidunt facilis. Atque iure ab fuga!
        Molestias quia minima ut illo ullam omnis pariatur eum inventore ipsam nisi labore incidunt numquam et debitis reprehenderit dignissimos ea blanditiis adipisci dicta nesciunt molestiae, unde aspernatur, tempora voluptatem. Id.
        Pariatur ratione corrupti ea eligendi animi saepe officia amet, facilis veniam aperiam earum quod velit, voluptate necessitatibus numquam quasi non, autem atque. Maiores magni quisquam officia amet eum a id.
        Reprehenderit recusandae veritatis illo, ex repellendus tempora facilis qui ullam cumque mollitia rem impedit vitae, laborum autem provident nostrum perferendis inventore accusamus excepturi consequatur ad. Molestiae eius sapiente odit. Quibusdam?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsam dolor molestiae a, vel magni labore possimus iure sapiente provident assumenda dolores voluptate mollitia facere ipsum illum adipisci itaque dicta dolorem?
        Sit, sapiente id optio mollitia commodi nostrum rerum autem libero animi aperiam illum. Perferendis libero totam doloremque obcaecati corporis, excepturi reprehenderit aliquid rem iste laboriosam, minima cumque praesentium, architecto iusto.
        Cum nobis aperiam eaque. Nostrum itaque, ratione, quam architecto veritatis ab laudantium dignissimos, voluptatem similique quisquam enim iure eos dolore temporibus totam cum provident ea est ullam quibusdam at fugiat.
        Quae quia officiis, corrupti consectetur sunt optio hic a, magni minus fugit itaque? Eos ducimus nihil qui nobis quod, repudiandae aspernatur consectetur! Unde porro at reiciendis tempore error voluptate ducimus.
        Odio, maxime ducimus. Ullam molestiae nisi architecto, ab aliquid quasi maiores quos voluptate accusantium minus nam exercitationem molestias quas veritatis dolore dolores rem natus eum. Nihil eveniet quidem beatae quod.
        Veniam, consequuntur consequatur expedita enim molestiae ex possimus optio adipisci eos quidem non? Corporis officia iste beatae autem id quae quod tempora cupiditate sed animi, obcaecati voluptates assumenda. Vero, magnam?
        At ullam a, quos mollitia quae culpa, voluptate labore facilis nihil nobis hic magnam nemo? Cumque, magnam! Ratione quisquam aspernatur, fugiat id molestiae nobis perspiciatis repudiandae beatae velit cupiditate minus.
        Dolores, vero earum? Odio ex nulla reiciendis a laudantium laborum tempore. Sed fugiat sapiente minus? Aspernatur iste quis est ducimus ex repellat blanditiis explicabo illum, quo cum? Quos, vel aliquam.
        Doloribus explicabo aliquid sequi. Hic dolorem voluptatem illum blanditiis minus optio voluptatibus sit adipisci ipsum corrupti, ut tenetur rem. Quod dolores deserunt deleniti officiis accusamus vitae animi quas eligendi accusantium!
        Nemo neque fuga perferendis similique debitis maxime sapiente consequuntur quaerat, repellat minus perspiciatis repudiandae? Sed sapiente molestiae repellat et quis optio animi facere, eius pariatur nemo, a illo consequuntur nisi!Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat neque velit recusandae ratione, laboriosam aut, natus exercitationem consequuntur architecto nam ut quis rerum. In quibusdam numquam dolorem odit reprehenderit omnis!
        Ducimus numquam molestiae doloribus repellat nisi non dolorum voluptatibus sed temporibus! Qui aspernatur doloremque accusantium eius veritatis possimus ipsa dolorum beatae consequuntur praesentium in, asperiores eum? Sequi provident dolorum quis.
        Delectus nihil, rerum repudiandae minus at libero totam a natus hic voluptatum tempora sapiente error dicta? Corrupti necessitatibus ad, porro, debitis fugiat aperiam consequuntur aut beatae voluptas accusamus quam magni?
        Quia, eum facilis rem, unde id maiores tenetur perspiciatis debitis iusto ad rerum est vero maxime libero incidunt dicta, aliquid nulla vel voluptas molestiae expedita quisquam asperiores! Rem, minima vel?
        Mollitia officia quidem deleniti, autem iste, ducimus commodi fugit velit cupiditate dolorum doloremque culpa eum totam quis, magni quia omnis minima! Impedit, nostrum. Asperiores, voluptates odit blanditiis ullam deserunt nulla!
        Sequi ipsa esse doloribus id, repellat nemo in unde, quae ratione recusandae eum nostrum explicabo facilis neque possimus deserunt libero quo ab maiores. Laborum, distinctio dolor facilis atque recusandae in.
        Magnam repellat perferendis sed in illum modi assumenda sint, pariatur accusantium adipisci saepe iure officia ut exercitationem tempore corporis, autem labore. Minima ea ut earum, nesciunt cum distinctio esse hic.
        Eius quis sapiente harum, sint illum totam vel voluptas consequuntur minus incidunt eaque! Molestiae reiciendis hic nobis ratione veritatis explicabo perferendis, saepe obcaecati eligendi sed ex. Reprehenderit quas consectetur exercitationem!
        In dolorum ex quo, temporibus nesciunt expedita similique, nisi, ullam quae veritatis corporis dolore! Ipsam quae, aliquam voluptatibus minus veniam, id, assumenda temporibus dolore error placeat eos magnam eligendi ab.
        Praesentium reiciendis sed exercitationem esse necessitatibus minus, corrupti debitis enim ducimus nihil! Enim odio voluptates commodi quis eligendi repudiandae dolores incidunt atque laborum libero. Odit natus laudantium pariatur. Inventore, ea!
</p>

@endsection